before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go generate -tags linux,darwin,windows,amd64,arm64 ./pkg/python
builds:
  - id: kluctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - id: linux-amd64
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--build-arg=ARCH=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/kluctl/kluctl:{{ .Version }}-amd64"
  - id: linux-arm64
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--build-arg=ARCH=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/kluctl/kluctl:{{ .Version }}-arm64"

docker_manifests:
  - name_template: ghcr.io/kluctl/kluctl:{{ .Version }}
    image_templates:
      - "ghcr.io/kluctl/kluctl:{{ .Version }}-amd64"
      - "ghcr.io/kluctl/kluctl:{{ .Version }}-arm64"

brews:
  - name: kluctl
    tap:
      owner: kluctl
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://kluctl.io/"
    description: "kluctl"
    install: |
      bin.install "kluctl"
    test: |
      system "#{bin}/kluctl version"
