apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kluctl
  name: kluctl-controller-leader-election-rolebinding
  namespace: kluctl-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kluctl-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: kluctl-controller
  namespace: kluctl-system
