{% set controller_version = (args.controller_version if args.controller_version is defined else controller_version) | default("v2.20.3") %}

resources:
  - crd.yaml
  - manager.yaml
  - rbac.yaml

patches:
  - target:
      kind: Deployment
      name: kluctl-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/kluctl/kluctl:{{ controller_version }}
{% if controller_version.endswith("-next-amd64") or controller_version.endswith("-next-arm64") %}
  - target:
      kind: Deployment
      name: kluctl-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
{% endif %}
