discriminator: kluctl.io-webui

args:
  - name: kluctl_image
    default: ghcr.io/kluctl/kluctl
  - name: kluctl_version
    default: v2.20.8
  - name: webui_args
    default: []
  - name: webui_envs
    default: []
  - name: webui_resources
    default: {}
