type: object
properties:
  args:
    type: object
    additionalProperties:
      type: string
  images:
    type: array
    items:
      type: object
      additionalProperties: false
      required:
        - image
        - resultImage
      properties:
        image:
          type: string
        resultImage:
          type: string
        deployedImage:
          type: string
        registryImage:
          type: string
        namespace:
          type: string
        deployment:
          type: string
        container:
          type: string
        versionFilter:
          type: string
        deployTags:
          type: array
          items:
            type: string
        kustomizeDir:
          type: string
