name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: unittests
        run: |
          pip install .
          python -munittest
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y git
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: pip install
        run: |
          pip install .
      - name: check-docs
        run: |
          python scripts/replace-commands-help.py
          if [ "$(git status --porcelain)" != "" ]; then
            echo "commands.md is not up-to-date. Run ./scripts/replace-commands-help.py to fix this!"
            exit 1
          fi
