name: tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: build-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            build-go-${{ runner.os }}-
      - name: Run unit tests
        run: |
          go test ./cmd/... ./pkg/... -v
      - name: Build kluctl (linux)
        run: |
          export CGO_ENABLED=0
          export GOARCH=amd64
          export GOOS=linux
          go build
          go test -c ./e2e
          mv kluctl kluctl-linux-amd64
          mv e2e.test e2e.test-linux-amd64
      - name: Build kluctl (darwin)
        run: |
          export CGO_ENABLED=0
          export GOARCH=amd64
          export GOOS=darwin
          go build
          go test -c ./e2e
          mv kluctl kluctl-darwin-amd64
          mv e2e.test e2e.test-darwin-amd64
      - name: Build kluctl (windows)
        run: |
          export CGO_ENABLED=0
          export GOARCH=amd64
          export GOOS=windows
          go build
          go test -c ./e2e
          mv kluctl.exe kluctl-windows-amd64.exe
          mv e2e.test.exe e2e.test-windows-amd64.exe
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            kluctl-linux-amd64
            kluctl-darwin-amd64
            kluctl-windows-amd64.exe
            e2e.test-linux-amd64
            e2e.test-darwin-amd64
            e2e.test-windows-amd64.exe

  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            binary-suffix: linux-amd64
          - os: macos-11
            binary-suffix: darwin-amd64
          - os: windows-2019
            binary-suffix: windows-amd64
        os: [ubuntu-20.04, macos-11, windows-2019]
      fail-fast: false
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: tests-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            tests-go-${{ runner.os }}-
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: setup-envtest
        shell: bash
        run: |
          make install-envtest
      - name: Run e2e tests
        shell: bash
        run: |
          EXE=
          if [ "${{ runner.os }}" == "Windows" ]; then
            EXE=.exe
          fi

          chmod +x ./binaries/*
          mv ./binaries/e2e.test-${{ matrix.binary-suffix }}$EXE ./e2e.test$EXE

          export KLUCTL_EXE=./binaries/kluctl-${{ matrix.binary-suffix }}$EXE
          make test-e2e-pre-built
