name: tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: build-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            build-go-${{ runner.os }}-
      - name: Run unit tests
        run: |
          go test ./cmd/... ./pkg/... -v
      - name: Build kluctl (linux)
        run: |
          make build GOARCH=amd64 GOOS=linux
          make test-e2e-build GOARCH=amd64 GOOS=linux
          mv ./bin/kluctl ./bin/kluctl-linux-amd64
          mv ./bin/kluctl-e2e ./bin/kluctl-e2e-linux-amd64
      - name: Build kluctl (darwin)
        run: |
          make build GOARCH=amd64 GOOS=darwin
          make test-e2e-build GOARCH=amd64 GOOS=darwin
          mv ./bin/kluctl ./bin/kluctl-darwin-amd64
          mv ./bin/kluctl-e2e ./bin/kluctl-e2e-darwin-amd64
      - name: Build kluctl (windows)
        run: |
          make build GOARCH=amd64 GOOS=windows
          make test-e2e-build GOARCH=amd64 GOOS=windows
          mv ./bin/kluctl.exe ./bin/kluctl-windows-amd64.exe
          mv ./bin/kluctl-e2e.exe ./bin/kluctl-e2e-windows-amd64.exe
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: |
            ./bin

  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            binary-suffix: linux-amd64
          - os: macos-11
            binary-suffix: darwin-amd64
          - os: windows-2019
            binary-suffix: windows-amd64
        os: [ubuntu-20.04, macos-11, windows-2019]
      fail-fast: false
    needs:
      - build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: tests-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            tests-go-${{ runner.os }}-
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: setup-envtest
        shell: bash
        run: |
          make install-envtest
      - name: Run e2e tests
        shell: bash
        run: |
          EXE=
          if [ "${{ runner.os }}" == "Windows" ]; then
            EXE=.exe
          fi

          chmod +x ./bin/*
          mv ./bin/kluctl-${{ matrix.binary-suffix }}$EXE ./kluctl$EXE
          mv ./bin/kluctl-e2e-${{ matrix.binary-suffix }}$EXE ./kluctl-e2e$EXE

          make test-e2e-pre-built
