name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: docs-check-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            docs-check-go-${{ runner.os }}-
      - name: Check links on changed files
        run: |
          make markdown-link-check
      - name: Verify commands help is up-to-date
        run: |
          make replace-commands-help
          if [ ! -z "$(git status --porcelain)" ]; then
            echo "replace-commands-help must be invoked and the result committed"
            git status
            git diff
            exit 1
          fi

  cross-compile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: cross-compile-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            cross-compile-go-${{ runner.os }}-
      - name: Build kluctl (linux)
        run: |
          make build GOARCH=amd64 GOOS=linux
      - name: Build kluctl (darwin)
        run: |
          make build GOARCH=amd64 GOOS=darwin
      - name: Build kluctl (windows)
        run: |
          make build GOARCH=amd64 GOOS=windows

  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            binary-suffix: linux-amd64
          - os: macos-11
            binary-suffix: darwin-amd64
          - os: windows-2019
            binary-suffix: windows-amd64
        os: [ubuntu-20.04, macos-11, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: tests-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            tests-go-${{ runner.os }}-
      - name: setup-envtest
        shell: bash
        run: |
          make install-envtest
      - name: Run unit tests
        shell: bash
        run: |
          make test-unit
      - name: Run e2e tests
        shell: bash
        run: |
          make test-e2e
