name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  unittests:
    runs-on: ubuntu-latest
    container: python:3.8.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: unittests
        run: |
          pip install .
          python -munittest
